### ISSUE TITLE
Improve the pattern matching around the subscription routeKey

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/bunnybus#62]
#### Context

For the `subscribe()` contract, the handlers currently contain a hash pair for `routeKey`/`event` assigned with a handler of signature `(message, ack, reject, requeue) => {}`.  The `routeKey` is used to bind queue to the exchange for message routing.  This `routeKey` can accept wild cards of the form `*` and `#`.  When we create a handler and assign it a full wild card or partially wild card value, the binding takes place on RabbitMQ, but BunnyBus doesn't respect it correctly.

Example,

`routeKey` of value `*` is used.  A messages comes through and lands in the queue with a concrete `routeKey` value of `systemA.message-created`.  This message will not be routed to the handler because the value does not match what was registered.  We need to put in place a better matching system than just checking `hasProperty()`.

This is the offending [LOC](https://github.com/xogroup/bunnybus/blob/master/lib/index.js#L481).

**Comment by dgmike** [comment]
This is happening with me, after 6 months of it was reported.

**Comment by lamchakchan** [comment]
Will look into it in the next two weeks.  We haven't ran into a use case needing to wild card yet so it hasn't been prioritize.

**Comment by lamchakchan** [comment]
This is now in the `master` branch.  I want to package the next release with one more issue.

**Comment by lamchakchan** [comment]
This is now in NPM under version `2.3.0`
