### ISSUE TITLE
Misleading call count when bunnyBus.publish is being spied and returns a promise

### ISSUE THREAD

**Issue by mattcphillips** [xogroup/bunnybus#76]
#### Context

* *node version*: 8.9.4
* *bunnybus version*: 2.3.0
* *environment* (node, browser): Node
* *any relevant modules used with* (eslint, mocha, etc.): Sinon, Bluebird
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce ?

1. In your tests, set a `sinon` spy on `bunnyBus.publish` like so: `sinon.spy(bunnyBus, 'publish');`
2. Call`bunnyBus.publish` and chain a Promise (the default native Promise or any particular library) onto it instead of a callback.
3. `console.log(bunnyBus.publish.callCount)` after the call and see that it is 2 instead of the expected 1. If you look at the `args` passed to the two spied calls, they are identical. The event is actually only published once but the spy leads you to believe that it was published twice.

#### What result did you expect ?
When you spy on `bunnyBus.publish`, call `bunnyBus.publish` once and return a Promise, then the spy should only see one call of `bunnyBus.publish`.

#### What result did you observe ?
When you spy on `bunnyBus.publish`, call `bunnyBus.publish` once and return a Promise, then the spy tracks two identical calls of `bunnyBus.publish`.

The problem seems to be happening [here](https://github.com/xogroup/bunnybus/blob/master/lib/index.js#L435) in the code. `publish` is called once with the original invocation, and then it is called again if no callback was provided. This results in the `sinon` spy accurately registering two calls when the rabbit event was only published once. If you are spying on `bunnyBus.publish` in your tests and expecting each call to represent an event that was published then this behavior is misleading.

**Comment by lamchakchan** [comment]
I was able to validate this through the following example utilizing the `Promise` interface 

```
'use strict';

const BunnyBus = require('bunnybus');
const bunnyBus = new BunnyBus();
const sinon = require('sinon');

const spy = sinon.spy(bunnyBus, 'publish');

async function main() {
    //create a subscription
    await bunnyBus.subscribe('queue1', { 
        'create-event' : (message, ack) => {
            // console.log(message.comment);
            console.log(spy);
            ack();
        }});


    //publish to the above subscription
    bunnyBus.publish({ event : 'create-event', comment : 'hello world!' });
};

main();```

and compared the `callCount` with a `callback` interface.

```
'use strict';

const BunnyBus = require('bunnybus');
const bunnyBus = new BunnyBus();
const sinon = require('sinon');

const spy = sinon.spy(bunnyBus, 'publish');

async function main() {
    //create a subscription
    await bunnyBus.subscribe('queue1', { 
        'create-event' : (message, ack) => {
            // console.log(message.comment);
            console.log(spy);
            ack();
        }});


    //publish to the above subscription
    bunnyBus.publish({ event : 'create-event', comment : 'hello world!' }, () => {});
};

main();
```
