### ISSUE TITLE
`retryCount` of messages in error queue affects message processing

### ISSUE THREAD

**Issue by Gordon-Feng** [xogroup/bunnybus#95]
### Context

* *bunnybus version*: 4.2.1

### Steps
* *When the `retryCount` of a message is equal `maxRetryCount`, bunnybus will auto reject the message and put it into an error queue;*
* *The message in error queue, its `headers.RetryCount` will be equal to `maxRetryCount` https://github.com/xogroup/bunnybus/blob/master/lib/index.js#L644*
* *`retryCount` will affects message processing when consume the error queue.
https://github.com/xogroup/bunnybus/blob/master/lib/index.js#L519*

### Expect
* *Remove or rename `retryCount` when reject a message;*

**Comment by dhinklexo** [comment]
We do this to prevent a "poison message" (a message that can never be processed) from locking services. 

If you need to process messages that have hit their max retry, raise your max retry temporarily and shovel the messages from the error queue to the operational queue through the rabbitmq admin.
